### ISSUE TITLE
How exact have you reproduce the experiment result？

### ISSUE THREAD

**Issue by guotong1988** [graykode/gpt-2-Pytorch#4]
Thank you very much.

**Comment by graykode** [comment]
Hello. Do you mean the result table of the paper?

**Comment by guotong1988** [comment]
Yes, but maybe you can achieve lower score with smaller parameters.

**Comment by graykode** [comment]
No. I dont experiment yet, using paper data. It is just simple text generator used gpt 2 model.
Do you have a interest in making a reproduction of paper result?
Thanks.

**Comment by guotong1988** [comment]
I will try.
